version: "3.9"
services:
  redis:
    container_name: cache
    image: redis:alpine
    volumes:
      - redis-data:/data/redis
    networks:
      - stockstalker-network
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    image: backend:$TAG
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./controllers:/usr/src/app/controllers
      - ./data:/usr/src/app/data
      - ./middleware:/usr/src/app/middleware
      - ./models:/usr/src/app/models
      - ./routes:/usr/src/app/routes
      - ./utils:/usr/src/app/utils
      - ./app.js:/usr/src/app/app.js
    env_file:
      - .env
    ports:
      - 8080:3000
    networks:
      - stockstalker-network
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  stockstalker-network:
    driver: bridge
