version: "3.9"
services:
  redis:
    container_name: cache
    image: redis:alpine
    volumes:
      - redis-data:/data/redis
    networks:
      - stockstalker-network
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8080:3000
    networks:
      - stockstalker-network
    depends_on:
      - redis
    command: npm test

volumes:
  redis-data:

networks:
  stockstalker-network:
    driver: bridge
