name: Test Backend

on:
  push:
    branches-ignore:
      - 'production'
    paths-ignore:
      - '**.md'
      - 'Makefile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint with Prettier and Eslint
        run: |
          npm run lint

      - name: Test with Mocha & Chai
        run: |
          npm run coverage
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          PREDICTOR_API: ${{ secrets.PREDICTOR_API }}
          ROBINHOOD_API: ${{ secrets.ROBINHOOD_API }}
          STOCK_DATA_API: ${{ secrets.STOCK_DATA_API }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Docker Image Security Test with Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
        with:
          image: node:lts-alpine
          args: --fail-on=upgradable

      - name: Security Test with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
        with:
          args: --fail-on=upgradable --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          status: FAILED
          color: danger
